### ISSUE TITLE
Package.json | syntax for "test" and "push" pre-commit hooks fail on Windows machines

### ISSUE THREAD

**Issue by aVileBroker** [Headstorm/foundry-ui#358]
There was an effort made by @dawsonbooth to do this, but it is currently in a state that only works in mac/linux shells. A solution that works in both would be ideal, barring that some OS detection which runs a different script?

**Comment by dawsonbooth** [comment]
I believe I only updated the `lint` and `prettier` scripts to work in all platforms. This was by [wrapping the glob patterns in single-quotes](https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784) in order that the shell's own glob parsing does not interfere with that of eslint and prettier.

It looks like the `test` and `push` hooks may need something different since there do not seem to be any glob patterns exposed in the commands.
